name: CI
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Build and copy static files to server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install deps
        run: yarn install --network-concurrency 1
      - name: Build project
        run: yarn build
      - name: Copy build to server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.REMOTE_HOST}}
          username: ${{secrets.REMOTE_HOST}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          source: "build"
          target: "emr-doc"